### ISSUE TITLE
Corrupted calendar options

### ISSUE THREAD

**Issue by Edenhofer** [AMKohn/iChrome#21]
![screenshot from 2015-04-04 21-13-32](https://cloud.githubusercontent.com/assets/7541458/6994173/7ccfeb88-db0f-11e4-8a34-87098da484a4.png)

There is no option to chose a calender, therefore it only displays "Glass developer hangout [...]"
I guess a picture would serve as a better description...

**Comment by AMKohn** [comment]
I believe this one is caused by a bug in the new OAuth library regarding a lack of rounding for subpixel values when creating the authorization dialog.  That would prevent you from being able to grant access.

[This](https://github.com/AMKohn/iChrome/commit/94333216ddeb47c46dac8bdc855f4dd05fdfd5bb) commit fixes it but it is _not_ included in the delayed update since I don't have the ability to update the update package until they approve or reject it.
