### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by Edenhofer** [AMKohn/iChrome#22]
In the installation guide (first page) you refer to not a not existing application. This because you have removed https://chrome.google.com/webstore/detail/iccjgbbjckehppnpajnmplcccjcgbdep from the play store.

Btw. why have you removed it, i used it since then and it worked.

**Comment by AMKohn** [comment]
This is a dupe of #19.  There are a few small (but significant) bugs in the latest version that I discovered shortly after releasing.  I immediately released a bugfix update that was flagged for manual review in the webstore.

I've since been trying anything I can to accelerate the process with no luck.
