### ISSUE TITLE
Flash content is not dispayed

### ISSUE THREAD

**Issue by rinaldus** [AMKohn/iChrome#24]
I tried to add iframe with my favorite clock in SWF format from my site but it doesn't show. I tried to create separate Web page with it (http://rinaldus.ru/clock.html) and inserted to HTML widget, but it also doesn't show. Is avaiable to display flash content with ichrome?

**Comment by AMKohn** [comment]
Flash objects were working a little while ago, but apparently aren't now due to the content security policy.  There does not appear to be a way to enable them without disabling the entire policy.

The sandbox on the iFrame widget also disables plugins, which due to the design of sandboxes can't be re-enabled, but you should be able to use the HTML widget with an iframe.

Avi
