### ISSUE TITLE
Feature Request: Multiple gmail accounts

### ISSUE THREAD

**Issue by thinkingmedia** [AMKohn/iChrome#27]
Right now iChrome shows a link for gmail on the top bar that points to

https://mail.google.com/mail

A lot of people have multiple gmail accounts. One for personal and one for work. These have different email addresses, but they can easily be accessed following this URL pattern.

https://mail.google.com/mail/u/0
https://mail.google.com/mail/u/1
https://mail.google.com/mail/u/2

The above would be for a user with 3 accounts linked to gmail.

I would like to be able to have my personal and work emails on the top bar. If that's possible?

Thanks,

**Comment by AMKohn** [comment]
Hi!

Yes, it is. You can add up to three custom links from the settings (under your picture at the top right) under general.

Thank you again for your help and advice with the restructure last year. I've gained a lot of experience since then, your advice really helped to set me on the right path! iChrome has come a long way (100,000 users!) and I'll be rolling out Pro plans with a bunch of other changes around January (work on those is happening in a separate branch).

**Comment by thinkingmedia** [comment]
Sorry, I should have looked in the settings first. lol

You have come along way on this project since last year. I constantly see your commit messages in my github feed, and I think "this guy just keeps on going". I'm so happy for you that you've reached an amazing 100k users.

You can count on me buying a pro plan!

**Comment by AMKohn** [comment]
No problem!

I didn't realize those showed up in the feed! I try, I'm hoping iChrome can grow into a real business and much more than iGoogle ever was.

Awesome! I hope the features will be well worth it!
