### ISSUE TITLE
Ugly advertisement at the center of my view

### ISSUE THREAD

**Issue by mcastril** [AMKohn/iChrome#49]
Since a few days ago I'm seeing an ugly advertisement in the first column of my view, just in the middle, screwing up all the layout.

I didn't ask for any PRO feature, and there ain't any new functionality in iChrome, so I guess this is a mistake.

**Comment by AMKohn** [comment]
As it is iChrome simply isn't making enough money to be sustainable. That leaves me with three choices: sell it (the new owner would certainly inject ads in other sites like I'm sure you've seen), let it slowly break down, or try to increase revenue a little so I can keep it afloat and work on expanding and improving it.

I know ads are often annoying, and I tried to pick the least intrusive option that still generates the needed revenue. I know the placement might be inconvenient, I'm working on a more options right now and hope to have them out Monday or Tuesday.

Thank you for your patience and understanding,
Avi

**Comment by jscheel** [comment]
Hi Avi, I know this is probably a frustrating time for you with the introduction of ads. Can I ask where the majority of costs are coming from? Is it hard operational costs, or is it your manpower for development and support of the extension? Just wondering if there are some ways to help reduce costs for you, or if it's more a matter of the extension requiring too much of your unpaid time.

**Comment by AMKohn** [comment]
@jscheel Very, but I think the bottom placement option I'll be adding will really help with most users' issues with the ad,

Both. I need to rework and expand the server infrastructure which I expect will eat up the current revenue (which isn't that significant, people are generally happy with the free version and aren't interested in Pro) and my own time is getting very scarce and will only get more so.

It's been 3 years and I can't afford to keep putting the time in that I have. I'd like to sell it to a buyer interested in developing it further and not using it to deliver ads, but I haven't been able to find one. At this point, I'm trying to get it on more stable monetary footing. Like you said in your webstore review, this is somewhat of a last ditch effort.

I'd like to keep working on iChrome, but I simply can't afford to as it is. It's been growing pretty steadily (230K weekly active users right now) and if I can grow it into an actual business that'll be better for everyone.

**Comment by jscheel** [comment]
@AMKohn hmm, that's a tough situation. Making enough to cover your server costs and making enough for it to justify the time sink it has become are two very different things. Have you thought about doing in-context ads in the rss feeds? Also, what are the major server-side cost centers? Anything some brainstorming with some of us other developers might help with?

**Comment by AMKohn** [comment]
@jscheel Those are a possibility, but I'd think people would have much more of an issue with their feed items getting messed with than a few widgets being pushed out of the way.

I should have put more thought into the default placement and placement options, but from the feedback I've received, excluding the people that condemn anything remotely related to ads (which run the free web), most users only have an issue with the placement and not the ad itself. I'm hoping the new options I'll try to get out tomorrow will really help with that.

One of those is a floating footer ad like this that I'm thinking might make a better default placement:

![screenshot 124](https://cloud.githubusercontent.com/assets/2001842/20467048/0547b7b2-af4d-11e6-90c8-ba76146655dd.png)

versus the current setup like this:

![image](https://cloud.githubusercontent.com/assets/2001842/20467106/07a79418-af4e-11e6-9a2a-b6c217b69b4e.png)

What do you think?

**Comment by jscheel** [comment]
@AMKohn hmm, that may be better, but you will definitely need to make sure to add extra padding at the footer to account for it. Or, instead of floating, you could make it fixed, and condense the scrolling of the actual dashboard to the space minus the ad. Either way would work. Also, have you considered a https://pinboard.in style approach to pricing (from before he went to yearly). Basically, it was a one-time purchase, with the price going up proportionately to the number of paid users.

**Comment by AMKohn** [comment]
@jscheel Thanks for the feedback.

Interesting. You mean going down so he makes the same money, right?

**Comment by jscheel** [comment]
@AMKohn no, the price actually raised as more people subscribed. It created a form of artificial urgency to the purchase decision.

**Comment by mcastril** [comment]
Thanks for all the answers. In fact I also was going to suggest an "ad-free" version, for the ones that are happy enough with the free features, but cheaper than the PRO version. Maybe a one-time purchase, as jscheel says could be a good solution.

You could put a minimum price and give the oportunity to put more money for the ones that want to donate more, like Wikipedia campaings or Humble bundle do.

**Comment by jscheel** [comment]
@AMKohn do I spy sponsored ads in the news feed? Could be an elegant solution. Are you seeing an uptick in revenue from it?

**Comment by AMKohn** [comment]
@jscheel The plan is to test adding 1-2 personalized articles, but they're not supposed to be live yet.

Did you see any marked with an icon, or are you just referring to the footer?

Regarding the general state of ads: I've been monitoring things closely and the vast majority of users seem to be perfectly fine with them. iChrome's actually grown a bit since the addition and the webstore only showed about 400 total extra uninstallations (from 230k users), with every other statistic I track agreeing. I've also received good feedback on them, although there were definitely a number of people very upset with the change. In short, I think the ads are here to stay.

I'll probably add a lifetime ad-free-only plan like @mcastril suggested, but that will involve work in iChrome itself since the whole authentication system works on a boolean isPro parameter, which will need to be changed.

What price do you think would be reasonable for that? uTorrent charges $4.95/year vs $20/year for the regular product, but that doesn't avoid the whole yearly plan issue and I don't know about the price point.

**Comment by AMKohn** [comment]
@robclancy Being open source provides a certain level of transparency, you can see exactly what code is being run on your computer and a log of what's changed. I feel this is important, particularly for a Chrome extension given the potential for the privileges it has to be abused (not to scare anyone, but the "all sites" permission that 99% of extensions have can be used to clean you out fairly easily, extensions are often as dangerous as an installed program).

Nothing whatsoever. The issues and costs with iChrome are due to its scale. A big part of the services I offer is the maintenance of existing widgets and the upkeep of the various services iChrome relies on (all the Google and iChrome APIs, etc., kindly don't piggyback on them for anything serious). Also, as per the license, you can't use the iChrome name and you must provide visible credit back to iChrome/me, so you can't launch an "iChrome Free" extension on the webstore, although you can do "My homepage+" or whatever else you want.

Google did add Now to Chrome, but they've since removed it.

I've decided to add an ad-free lifetime plan for $10. I'll try to get an update out with that Sunday or Monday, and see how that goes.
